Vagrant.configure(2) do |config|
  config.vm.box_check_update = false
  config.vm.provider 'virtualbox' do |vb|
    vb.cpus = 4
  end

  if ENV['DOTFILES']
    config.vm.provision 'dotfiles-fetch', type: 'shell' do |shell|
      shell.privileged = false
      shell.inline = <<-SHELL
        sudo apt-get update
        sudo apt-get install -y git
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts
        ssh -T git@github.com
        git clone git@github.com:justcxx/dotfiles.git
      SHELL
    end

    config.vm.provision 'dotfiles-setup', type: 'ansible_local' do |ansible|
      ansible.playbook = 'playbook.yml'
      ansible.provisioning_path = '/home/ubuntu/dotfiles'
      ansible.tags = ENV['TAGS']
    end
  end
end
