Vagrant.configure(2) do |config|
  config.ssh.forward_agent = true
  config.vm.box_check_update = false
  config.vm.network 'forwarded_port', guest: '35729', host: '35729' # livereload
  config.vm.provider 'virtualbox' do |vb|
    vb.cpus = 4
  end
end
