" { Plugins
    call plug#begin('~/.vim/plugged')

    " General
    Plug 'tpope/vim-commentary'
    Plug 'tpope/vim-dispatch'
    Plug 'tpope/vim-endwise'
    Plug 'tpope/vim-fugitive'
    Plug 'tpope/vim-git'
    Plug 'neomake/neomake'
    Plug 'tpope/vim-repeat'
    Plug 'tpope/vim-sensible'
    Plug 'tpope/vim-surround'
    Plug 'janko-m/vim-test'

    " Search and navigation
    Plug 'dyng/ctrlsf.vim'
    Plug 'jlanzarotta/bufexplorer'
    Plug 'ctrlpvim/ctrlp.vim'
    Plug 'jasoncodes/ctrlp-modified.vim'
    Plug 'scrooloose/nerdtree'

    " Autocomplete
    Plug 'jiangmiao/auto-pairs'
    Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
    Plug 'Shougo/neocomplete'
    Plug 'Shougo/neosnippet'
    Plug 'Shougo/neosnippet-snippets'

    " Advanced
    Plug 'vim-airline/vim-airline'
    Plug 'vim-airline/vim-airline-themes'
    Plug 'ConradIrwin/vim-bracketed-paste'
    Plug 'airblade/vim-gitgutter'
    Plug 'kassio/neoterm'
    Plug 'majutsushi/tagbar'
    Plug 'mbbill/undotree', { 'on': 'UndotreeToggle' }
    " Plug 'Valloric/MatchTagAlways'
    Plug 'terryma/vim-multiple-cursors'
    Plug 'Shougo/vimproc.vim', {'do' : 'make'}
    Plug 'kana/vim-textobj-user'

    " Tools integration
    Plug 'hashivim/vim-vagrant'
    Plug 'wfleming/vim-codeclimate'
    Plug 'rizzatti/dash.vim'

    " Languages support
    Plug 'chase/vim-ansible-yaml'
    Plug 'kchmck/vim-coffee-script'
    Plug 'othree/html5.vim'
    Plug 'tpope/vim-haml'
    Plug 'tpope/vim-markdown'
    Plug 'slim-template/vim-slim'
    Plug 'tmux-plugins/vim-tmux'
    Plug 'Glench/Vim-Jinja2-Syntax'
    Plug 'lmeijvogel/vim-yaml-helper'
    Plug 'kylef/apiblueprint.vim'
    Plug 'IN3D/vim-raml'

    " Clojure
    Plug 'guns/vim-clojure-highlight'
    Plug 'guns/vim-clojure-static'
    Plug 'guns/vim-slamhound'
    Plug 'tpope/vim-classpath'
    Plug 'tpope/vim-fireplace'
    Plug 'tpope/vim-salve'
    Plug 'venantius/vim-eastwood'
    Plug 'venantius/vim-cljfmt'
    Plug 'vim-scripts/paredit.vim'

    " Elixir
    Plug 'elixir-lang/vim-elixir'
    Plug 'thinca/vim-ref'
    Plug 'awetzel/elixir.nvim', { 'do': 'yes \| ./install.sh' }
    Plug 'slashmili/alchemist.vim'
    Plug 'c-brenn/phoenix.vim'

    " " Erlang
    " Plug 'vim-erlang/vim-erlang-runtime'
    " Plug 'vim-erlang/vim-erlang-compiler'
    " Plug 'vim-erlang/vim-erlang-omnicomplete'
    " Plug 'vim-erlang/vim-erlang-tags'

    " Haskell
    Plug 'eagletmt/ghcmod-vim'
    Plug 'eagletmt/neco-ghc'
    Plug 'mpickering/hlint-refactor-vim'
    Plug 'neovimhaskell/haskell-vim'
    Plug 'twinside/vim-hoogle'

    " JavaScript
    Plug 'pangloss/vim-javascript'
    Plug 'mxw/vim-jsx'
    Plug 'mtscout6/vim-cjsx'
    Plug 'flowtype/vim-flow'
    Plug 'moll/vim-node'
    Plug 'benjie/neomake-local-eslint.vim'

    " Ruby, Rails
    Plug 'tpope/vim-bundler'
    Plug 'tpope/vim-rails'
    Plug 'vim-ruby/vim-ruby'
    Plug 'sunaku/vim-ruby-minitest'
    Plug 'thoughtbot/vim-rspec'
    Plug 'tpope/vim-rvm'
    Plug 'p0deje/vim-ruby-interpolation'

    " Themes
    Plug 'nanotech/jellybeans.vim'

    call plug#end()

    " { Plugin configuration
        let mapleader=","

        " { Alchemist (Elixir)
            let g:alchemist_iex_term_size = 15
            let g:alchemist_iex_term_split = 'split'
            let g:alchemist_tag_disable = 1
            let g:elixir_autobuild = 1
            let g:elixir_docpreview = 1
        " }

        " { BufExplorer
            let g:bufExplorerShowRelativePath=1
        " }

        " { Fireplace (Clojure)
            nmap <Leader>r :RunTests<CR>
            autocmd User FireplacePreConnect call fireplace#register_port_file(expand('./nrepl-port'), '/')
        " }

        " { Ghc-mod (Haskell)
            hi ghcmodType ctermbg=yellow
            let g:ghcmod_type_highlight = 'ghcmodType'
        " }

        " { Haskell-vim
            let g:haskellmode_completion_ghc = 0
        " }

        " { Jellybeans
            colorscheme jellybeans
            let g:jellybeans_use_term_background_color = 1
        " }

        " { Vim-jsx
            let g:jsx_ext_required = 0
        " }

        " { Vim-markdown
            let g:markdown_fenced_languages = ['clojure', 'ruby']
        " }

        " { Neomake
            let g:neomake_javascript_enabled_makers = ['eslint', 'flow']
            let g:neomake_elixir_enabled_makers = ['credo', 'mix']
        " }

        " { Neoterm
            let g:neoterm_automap_keys = ',tt'
            let g:neoterm_use_relative_path = 1
            let g:neoterm_shell = 'bash -login'

            nnoremap <silent> ,tc :call neoterm#kill()<cr>
            nnoremap <silent> ,th :call neoterm#close()<cr>
            nnoremap <silent> ,tl :call neoterm#clear()<cr>
            nnoremap <silent> <f10> :TREPLSendFile<cr>
            nnoremap <silent> <f9> :TREPLSend<cr>
            vnoremap <silent> <f9> :TREPLSend<cr>

        " }

        " { NERDTree
            let NERDTreeIgnore = ['\.pyc$']

            nmap <C-\> :NERDTreeFind<CR>
            nmap <silent> <leader><leader> :NERDTreeToggle<CR>
        " }

        " { CtrlSF
            nmap     <C-F>f <Plug>CtrlSFPrompt
            vmap     <C-F>f <Plug>CtrlSFVwordPath
            vmap     <C-F>F <Plug>CtrlSFVwordExec
            nmap     <C-F>n <Plug>CtrlSFCwordPath
            nmap     <C-F>p <Plug>CtrlSFPwordPath
            nnoremap <C-F>o :CtrlSFOpen<CR>
            nnoremap <C-F>t :CtrlSFToggle<CR>
            inoremap <C-F>t <Esc>:CtrlSFToggle<CR>
        " }

        " { Vim-test
            let test#strategy = "neoterm"

            nmap <silent> <leader>rt :TestSuite<CR>
            nmap <silent> <leader>rf :TestFile<CR>
            nmap <silent> <leader>rn :TestNearest<CR>
            nmap <silent> <leader>rr :TestLast<CR>
            nmap <silent> <leader>g :TestVisit<CR>
        " }
    " }
" }

" { Genaral options
    set cb=unnamedplus
    set completefunc=syntaxcomplete#Complete
    set cursorline
    set diffopt+=vertical
    set expandtab
    set hidden
    set hlsearch
    set ignorecase
    set lazyredraw
    set nobackup
    set nocursorline
    set noswapfile
    set nowb
    set nowrap
    set number
    set pastetoggle=<F2>
    set shiftwidth=4
    set smartcase
    set splitbelow
    set splitright
    set t_Co=256
    set tabstop=4
" }

" The Silver Searcher
if executable('ag')
  " Use ag over grep
  set grepprg=ag\ --nogroup\ --nocolor

  " Use ag in CtrlP for listing files.
  " Lightning fast and respects .gitignore
  let g:ctrlp_user_command = 'ag -l --nocolor -g "" %s'

  " ag is fast enough that CtrlP doesn't need to cache
  let g:ctrlp_use_caching = 0
endif

" ================ Persistent Undo ==================
" Keep undo history across sessions, by storing in file.
" Only works all the time.
if has('persistent_undo')
  silent !mkdir ~/.vim/backups > /dev/null 2>&1
  set undodir=~/.vim/backups
  set undofile
endif

" ==================== KeyMap ========================
nmap <F8> :TagbarToggle<CR>
nnoremap <F5> :UndotreeToggle<cr>

" Map ctrl-movement keys to window switching
map <C-k> <C-w><Up>
map <C-j> <C-w><Down>
map <C-l> <C-w><Right>
map <C-h> <C-w><Left>
nnoremap <silent> <bs> <C-w><Left>

" upper/lower word
nmap <leader>u mQviwU`Q
nmap <leader>l mQviwu`Q

nmap <silent> // :nohlsearch<CR>
noremap ,h1 :set hlsearch! hlsearch?<CR>

" set text wrapping toggles
nmap <silent> <leader>tw :set invwrap<CR>:set wrap?<CR>

" ctrlp git modified
map <Leader>m :CtrlPModified<CR>
map <Leader>M :CtrlPBranch<CR>

" Allows you to enter sudo pass and save the file
" when you forgot to open your file with sudo
cmap w!! %!sudo tee > /dev/null null%

" Allow to copy/paste between VIM instances
" copy the current visual selection to ~/.vbuf
vmap <Leader>y :w! ~/.vbuf<CR>
" copy the current line to the buffer file if no visual selection
nmap <Leader>y :.w! ~/.vbuf<CR>
" paste the contents of the buffer file
nmap <Leader>p :r ~/.vbuf<CR>

augroup global_au
    au!

    au BufWritePost * Neomake
    au BufWritePost init.vim,.vimrc source %

    " Automatically removing all trailing whitespace
    au BufWritePre * :%s/\s\+$//e

    au BufRead,BufNewFile {Capfile,Gemfile,Guardfile,Vagrantfile,*.prawn} set ft=ruby
    au BufRead,BufNewFile {.babelrc,.eslintrc} set ft=json
augroup END

augroup ft_markdown
    au!
    au FileType markdown setlocal spell spelllang=ru_ru,en_us
    au FileType markdown setlocal wrap
augroup END

augroup ft_gitcommit
    au!
    au FileType gitcommit setlocal spell spelllang=en_us
augroup END

augroup ft_haskell
    au FileType haskell setlocal makeprg=stack
    au FileType haskell setlocal omnifunc=necoghc#omnifunc

    autocmd BufWritePost *.hs GhcModCheckAndLintAsync

    " { Mappings
        au FileType haskell nnoremap <buffer> gll :Neomake<CR>
        au FileType haskell nnoremap <silent><buffer> gfs :GhcModSplitFunCase<CR>
        au FileType haskell nnoremap <silent><buffer> git :GhcModTypeInsert<CR>
        au FileType haskell nnoremap <silent><buffer> gtt :GhcModType<CR>
        au FileType haskell nnoremap <silent><buffer> gct :GhcModTypeClear<CR>
    " }
augroup END

augroup set_shift_width
    au!
    au FileType ruby  setl sw=2 sts=2 et
    au FileType eruby setl sw=2 sts=2 et
    au FileType javascript setl sw=2 sts=2 et
    au FileType yaml setl sw=2 sts=2 et
augroup END

augroup set_omnifunc
    au!
    au FileType css            setlocal omnifunc=csscomplete#CompleteCSS
    au FileType html,markdown  setlocal omnifunc=htmlcomplete#CompleteTags
    au FileType javascript     setlocal omnifunc=javascriptcomplete#CompleteJS
    au FileType python         setlocal omnifunc=pythoncomplete#Complete
    au FileType xml            setlocal omnifunc=xmlcomplete#CompleteTags
augroup END

command! J :%!python -mjson.tool
